# Generated by Django 4.2.2 on 2023-07-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pdf_file", models.FileField(null=True, upload_to="pdf_files/")),
                ("extracted_text", models.TextField(null=True)),
            ],
        ),
    ]
