# Generated by Django 4.2.2 on 2023-08-05 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("DreamedJobAI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to="DreamedJobAI/static/DreamedJobAI/assets/img/user_pp"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("about", models.CharField(max_length=500)),
                ("desired_job_title", models.CharField(max_length=100)),
                ("desired_location", models.CharField(max_length=100)),
                ("desired_job_description", models.CharField(max_length=500)),
                ("desired_compensantion", models.FloatField(blank=True, null=True)),
                ("desired_benefits", models.CharField(max_length=200)),
                ("desired_industry", models.CharField(max_length=50)),
                ("desired_start_day", models.DateTimeField(max_length=50)),
                ("urgency", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=150)),
                ("contact_number", models.CharField(max_length=250)),
                ("video_conference", models.CharField(max_length=250)),
                ("linkedin", models.CharField(max_length=250)),
                ("github", models.CharField(max_length=250)),
                ("website", models.CharField(max_length=250)),
                ("messages", models.CharField(max_length=250)),
                ("other", models.CharField(max_length=250)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
