# Generated by Django 4.2.2 on 2023-08-05 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "DreamedJobAI",
            "0003_remove_profile_about_remove_profile_desired_benefits_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilepreferences",
            name="picture",
        ),
    ]
