# Generated by Django 4.2.2 on 2023-08-07 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0004_remove_profilepreferences_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="full_name",
        ),
    ]
