# Generated by Django 4.2.2 on 2023-08-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "DreamedJobAI",
            "0006_alter_profile_contact_number_alter_profile_github_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                default="DreamedJobAI/assets/img/user.png", upload_to="user_pp/"
            ),
        ),
    ]
