# Generated by Django 4.2.2 on 2023-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0007_alter_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(default="user_pp/user.png", upload_to="user_pp/"),
        ),
    ]
