# Generated by Django 4.2.2 on 2023-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0008_alter_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="messages",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="video_conference",
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(default="Not specified", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, default="Not specified", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_number",
            field=models.IntegerField(
                blank=True, default="Not specified", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.CharField(blank=True, default="Not specified", max_length=250),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.CharField(blank=True, default="Not specified", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="other",
            field=models.CharField(blank=True, default="Not specified", max_length=250),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.CharField(blank=True, default="Not specified", max_length=250),
        ),
    ]
