# Generated by Django 4.2.2 on 2023-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0009_remove_profile_messages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="contact_number",
            field=models.IntegerField(blank=True, default="Not specified"),
        ),
    ]
