# Generated by Django 4.2.2 on 2023-08-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "DreamedJobAI",
            "0015_alter_profile_contact_number_alter_profile_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepreferences",
            name="desired_start_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_urgent", "Very Urgent"),
                    ("somewhat_urgent", "Somewhat Urgent"),
                    ("not_urgent", "Not Urgent"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
