# Generated by Django 4.2.2 on 2023-08-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0016_alter_profilepreferences_desired_start_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.CharField(blank=True, default="Not specified"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.CharField(blank=True, default="Not specified"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="other",
            field=models.CharField(blank=True, default="Not specified"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, default="Not specified"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.CharField(blank=True, default="Not specified"),
        ),
    ]
