# Generated by Django 4.2.2 on 2023-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0017_alter_profile_github_alter_profile_linkedin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepreferences",
            name="desired_start_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Within 1 week", "Within 1 week"),
                    ("1-2 weeks", "1-2 weeks"),
                    ("2-4 weeks", "2-4 weeks"),
                    ("1-2 months", "1-2 months"),
                    ("More than 2 months", "More than 2 months"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
