# Generated by Django 4.2.2 on 2023-08-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0022_alter_profilepreferences_desired_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("link", models.URLField()),
                ("location", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("user_id", models.IntegerField()),
                ("suitability", models.CharField(max_length=200)),
                ("explanation", models.TextField()),
            ],
        ),
    ]
