# Generated by Django 4.2.2 on 2023-08-24 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0025_alter_suitablejobs_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
