# Generated by Django 4.2.2 on 2023-08-30 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DreamedJobAI", "0030_userprofilepreferences"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfilePreferences",
        ),
    ]
